### ISSUE TITLE
confused on how this actually works

### ISSUE THREAD

**Issue by zerolaser** [ashwanthkumar/gocd-build-badge-server#2]
Can you please update the README file  on how to set this up for the private github repo's.
also i dint see where this app will get the details from my private gocd server and update it  on the github ?

**Comment by ashwanthkumar** [comment]
@zerolaser This app is supposed to go with https://github.com/ashwanthkumar/gocd-build-badge-notifier. The notification plugin would push build status to this server. Then adding a following markdown

```
[![Build Status](https://HOST_OF_BADGE_SERVER.com/badge/Pipeline-Name)](http://ci-server:8153/go/tab/pipeline/history/Pipeline-Name)
```

would then display a build status image on the README of the private repo.

It was built for experimental purpose a few years ago. I have not been maintaining it, if you find it useful please do drop a note. I would be happy to fix any bugs or issues you might run into.
